### ISSUE TITLE
Data Mapping Code

### ISSUE THREAD

**Issue by GaaiWai** [Suiiyu/MS-CMR2019#1]
Hi,  your data mapping strategy is excellent , but sorry I can't figure out which code is data mapping, could you point out where is the related code, thanks

**Comment by Suiiyu** [comment]
Sorry for the late response. In fact the data mapping is a preprocess. As it is the classical histogram matching algorithm, I did not upload it. This is the referece [code](https://blog.csdn.net/mmmmmk_/article/details/82927411) of mine. I hope it can help you.
