### ISSUE TITLE
Could you send me the preprossesed data?Thanks.

### ISSUE THREAD

**Issue by Einshowstank** [Suiiyu/MS-CMR2019#3]

**Comment by Suiiyu** [comment]
Thanks for your attention. Please contact the organizer to get the dataset. I don't have the authority to propagate the data. [This](https://arxiv.org/abs/2006.12434) paper can help you find the organizer.

**Comment by Einshowstank** [comment]
Ok, I understand. Thanks for the reply!

发送自 Windows 10 版邮件应用

发件人: Sue
发送时间: 2021年6月22日 18:54
收件人: Suiiyu/MS-CMR2019
抄送: Hector; Author
主题: Re: [Suiiyu/MS-CMR2019] Could you send me the preprosseseddata?Thanks. (#3)

Thanks for your attention. Please contact the organizer to get the dataset. I don't have the authority to propagate the data. This paper can help you find out the organizer.
