### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by PLMMZY67** [Suiiyu/MS-CMR2019#4]
sorry to disturb you!I have downloaded the dataset from the official website.but when i try to open the .nii file in matlab or ITK-SNAP,I failed in both way.Can you open the original data sucessfully?

**Comment by Suiiyu** [comment]
[ Seg3D](http://sciinstitute.github.io/seg3d.pages/Manuals/Seg3DTutorial.html) and [3D Slicer](https://www.slicer.org/) can view the data. If you want to process the data, the [nibabel ](https://nipy.org/nibabel/) may help you (It is a python package). I am not familiar with the API of matlab. If you want to process it via matlab, you can adopt the Seg3D to convert data format.
